services:
  # 0. Must have a GPU available to run the model, so we check for that first
  gpu-check:
    image: nvidia/cuda:13.0.2-devel-ubuntu24.04
    container_name: gpu-check
    command: >
      sh -c "if command -v nvidia-smi > /dev/null 2>&1 && nvidia-smi --query --display=COMPUTE > /dev/null 2>&1; then
        return 0
      else
        return 1
      fi"
    deploy:
      resources:
        limits:
          memory: 512M      # Hard limit: Container will be killed if exceeded
        reservations:
          memory: 512M      # Soft limit: Minimum memory guaranteed to the container
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # 2. Runs llama.cpp server with the downloaded model
  llama-cpp:
    # if downloading the image from Docker Hub, use the line below. If building locally, use the line after that
    platform: linux/amd64
    image: llama-cpp
    container_name: llama-cpp
    build:
      context: ./llama.cpp
      dockerfile: .devops/cuda.Dockerfile
      # Adjust CUDA architectures to match your GPU(s):
      #   75 = Turing (RTX 2000),
      #   80 = Ampere (A100/RTX 3000),
      #   86 = Ampere (RTX 3000 consumer),
      #   89 = Ada (RTX 4000),
      #   90 = Hopper (H100)
      args:
        CUDA_VERSION: "13.0.2"
        CUDA_DOCKER_ARCH: "89"
    labels:
      # This tells autoheal to watch this container
      autoheal: true
    volumes:
      # Maps a local folder named 'models_cache' to the container's cache path
      - ../models_cache:/root/.cache/llama.cpp
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 3600s
    environment:
      - LC_ALL=C.utf8
    deploy:
      resources:
        limits:
          memory: 5G      # Hard limit: Container will be killed if exceeded
        reservations:
          memory: 5G      # Soft limit: Minimum memory guaranteed to the container
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md?plain=1#L101
    # --docker-repo ai/gemma4:E4B
    # --docker-repo ai/ministral3:8B-Q4_K_M
    # --docker-repo ai/qwen3.6:35B-A3B-UD-Q4_K_M
    # when needs jinja.
    # --jinja
    # --chat-template-file /root/.cache/llama.cpp/chat_template-v19.jinja
    # --chat-template-kwargs '{"preserve_thinking": true}'
    command: >
      --docker-repo ai/qwen3.5:9B-UD-Q4_K_XL
      --host 0.0.0.0
      --port 8080
      --n-cpu-moe 40
      --no-webui
      --parallel 1
      -fit off
      --dry-multiplier 0.8 
      --samplers "top_k;top_p;min_p;temperature;dry;typ_p;xtc"
      --no-context-shift
      --top-k 40
      --repeat-penalty 1.1
      --top-p 0.95
      --min-p 0.05
      --n-gpu-layers 99
      --no-mmap
      --batch-size 4096
      --ubatch-size 512
      -c 262144
      --swa-full
      --flash-attn on
      --cache-type-k q4_0 
      --cache-type-v q4_0
    networks:
      - shared-network    
  # 3. Runs the monitoring dashboard to visualize GPU usage and model performance
  monitor:
    image: ghcr.io/psalias2006/gpu-hot:latest
    container_name: monitor
    ports:
      - "1312:1312"
    depends_on:
      llama-cpp:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M      # Hard limit: Container will be killed if exceeded
        reservations:
          memory: 512M      # Soft limit: Minimum memory guaranteed to the container
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # 4. Autoheal when container fails and need to restart
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    depends_on:
      llama-cpp:
        condition: service_started
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 256M      # Hard limit: Container will be killed if exceeded

networks:
  shared-network:
    external: true
    name: ai-network
