services:
  # 0. Must have a GPU available to run the model, so we check for that first
  gpu-check:
    image: nvidia/cuda:13.0.2-devel-ubuntu24.04
    container_name: gpu-check
    command: >
      sh -c "if command -v nvidia-smi > /dev/null 2>&1 && nvidia-smi --query --display=COMPUTE > /dev/null 2>&1; then
        return 0
      else
        return 1
      fi"
    deploy:
      resources:
        limits:
          memory: 512M      # Hard limit: Container will be killed if exceeded
        reservations:
          memory: 512M      # Soft limit: Minimum memory guaranteed to the container
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # 2. Runs vllm server with the downloaded model
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    labels:
      # This tells autoheal to watch this container
      autoheal: true
    volumes:
      # Maps a local folder named 'models_cache' to the container's cache path
      - ../models_cache:/root/.cache
    ports:
      - "8080:8000"
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - VLLM_LOGGING_LEVEL=${VLLM_LOGGING_LEVEL} # Forces vLLM to output detailed step-by-step lifecycles
      - CUDA_LAUNCH_BLOCKING=1   # Forces CUDA to report errors instantly instead of asynchronously
      - HF_HUB_DISABLE_XET=1          # Disables erratic Xet streams for stable HTTP
      - HF_HUB_DOWNLOAD_TIMEOUT=300   # Extends timeout to 5 mins for massive Q4 shards
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 100
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 5G      # Hard limit: Container will be killed if exceeded
        reservations:
          memory: 5G      # Soft limit: Minimum memory guaranteed to the container
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    entrypoint: ["vllm", "serve", "Qwen/Qwen3.5-4B"]
    command: >
      --reasoning-parser qwen3
      --enable-auto-tool-choice 
      --tool-call-parser qwen3_coder   
      --max-model-len 10240
      --max-num-batched-tokens 1024
      --max-num-seqs  1               
      --gpu-memory-utilization 0.90
      --enable-chunked-prefill
      --enforce-eager
      --language-model-only
      --trust-remote-code
      --chat-template="{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n' + message['content'] + '<|im_end|>\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"

    networks:
      - shared-network    
  # 3. Runs the monitoring dashboard to visualize GPU usage and model performance
  monitor:
    image: ghcr.io/psalias2006/gpu-hot:latest
    container_name: monitor
    ports:
      - "1312:1312"
    depends_on:
      vllm:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 512M      # Hard limit: Container will be killed if exceeded
        reservations:
          memory: 512M      # Soft limit: Minimum memory guaranteed to the container
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # 4. Autoheal when container fails and need to restart
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    depends_on:
      vllm:
        condition: service_started
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 256M      # Hard limit: Container will be killed if exceeded

networks:
  shared-network:
    external: true
    name: ai-network
